### ISSUE TITLE
Unable to compile contract

### ISSUE THREAD

**Issue by sahni619** [mradkov/decentralized-dns#1]
Hi, 

I am unable to compile the contract using truffle. I get below issue while running command `truffle compile` inside contracts folder of ddns directory.

`/ddns/contracts/contracts/common/Destructible.sol:15:22: TypeError: Invalid type for argument in function call. Invalid implicit conversion from function () view returns (address) to address payable requested.
        selfdestruct(owner);
                     ^---^
/ddns/contracts/contracts/common/Destructible.sol:19:22: TypeError: Invalid type for argument in function call. Invalid implicit conversion from address to address payable requested.
        selfdestruct(_recipient);
                     ^--------^
Compilation failed. See above.
`
My Destructible.sol file is as below 

`pragma solidity >=0.4.22 <0.6.0;

import "./Ownable.sol";

/**
 * @title Destructible
 * @dev Base contract that can be destroyed by owner. All funds in contract will be sent to the owner.
 */
contract Destructible is Ownable {
  /**
   * @dev Transfers the current balance to the owner and terminates the contract.
   */
    function destroy() public onlyOwner {
        selfdestruct(owner);
    }

    function destroyAndSend(address _recipient) public onlyOwner {
        selfdestruct(_recipient);
    }
}`

**Comment by mradkov** [comment]
Can you try pulling the latest changes from the repo. `Destructible.sol` was removed in https://github.com/mradkov/decentralized-dns/commit/808d7218f7cefbbb543617d773c508e647e17d26

You shouldn't stumble upon this issue with the latest commits.

**Comment by sahni619** [comment]
I did pull the latest version but now a different issue 

`  /Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:11:3: Warning: This declaration shadows an existing declaration.
  function Migrations() public {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:3:1: The shadowed declaration is here:
contract Migrations {
^ (Relevant source part starts here and spans across multiple lines).



/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.18;
^----------------------^
,/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:11:3: SyntaxError: Functions are not allowed to have the same name as the contract. If you intend this to be a constructor, use "constructor(...) { ... }" to define it.
  function Migrations() public {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/vivek/decentralized-dns/smart-contract/contracts/mocks/Acknowledger.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;
^----------------------^
,/Users/vivek/decentralized-dns/smart-contract/contracts/mocks/EventEmitter.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;
^----------------------^
,/Users/vivek/decentralized-dns/smart-contract/contracts/mocks/Failer.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;
^----------------------^
,/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:11:3: Warning: This declaration shadows an existing declaration.
  function Migrations() public {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:3:1: The shadowed declaration is here:
contract Migrations {
^ (Relevant source part starts here and spans across multiple lines).

,/Users/vivek/decentralized-dns/smart-contract/contracts/Migrations.sol:20:5: TypeError: Name has to refer to a struct, enum or contract.
    Migrations upgraded = Migrations(new_address);
    ^--------^
Compilation failed. See above.    `

**Comment by mradkov** [comment]
Which version of truffle and solc are you using?

`truffle version`

**Comment by mradkov** [comment]
https://github.com/mradkov/decentralized-dns/commit/b7cd8a36539fbda4a214bf3990713c3b99817ff7 Fixes this issue, according to our Travis CI with `truffle@4` and `solc v0.4.25` ([view log here](https://travis-ci.org/mradkov/decentralized-dns/builds/476573044)). 

I haven't tested with the newest truffle version 5 and solc 0.5.0.

**Comment by sahni619** [comment]
Thanks for the info. I am able to compile now 👍
